"""Shared Promptfoo export helpers for EvalOps runner scripts."""

from __future__ import annotations

import sys

import yaml


def log(msg: str) -> None:
    print(msg, file=sys.stderr)


def error(msg: str) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)


def map_case_to_promptfoo(case: dict, target_manifest: dict) -> dict | None:
    entry: dict = {"vars": {"input": case.get("input", "")}}
    assertions = []

    expected = case.get("expected", {})
    must_include = expected.get("must_include") or []
    must_not_include = expected.get("must_not_include") or []
    rubric = expected.get("rubric") or ""

    evaluators = case.get("evaluators", {})
    rule_based = evaluators.get("rule_based", {})
    llm_judge = evaluators.get("llm_judge", {})

    assertion_policy = target_manifest.get("assertion_policy", {})
    allow_llm_rubric = assertion_policy.get("allow_llm_rubric", False)

    for item in must_include:
        assertions.append({"type": "contains", "value": item.strip() if isinstance(item, str) else item})

    for item in must_not_include:
        assertions.append({"type": "not-contains", "value": item.strip() if isinstance(item, str) else item})

    rule_contains = rule_based.get("contains") or []
    for item in rule_contains:
        if item and item not in must_include:
            assertions.append({"type": "contains", "value": item.strip() if isinstance(item, str) else item})

    rule_not_contains = rule_based.get("not-contains") or []
    for item in rule_not_contains:
        if item and item not in must_not_include:
            assertions.append({"type": "not-contains", "value": item.strip() if isinstance(item, str) else item})

    if rubric and llm_judge.get("enabled", False):
        if not rubric.strip():
            error(
                f"Case '{case.get('id', '?')}' has llm-rubric enabled but no rubric text configured."
            )
            return None
        if not allow_llm_rubric:
            error(
                f"Case '{case.get('id', '?')}' has llm-rubric but target policy "
                f"prohibits unconfigured llm-rubric assertions."
            )
            return None
        assertions.append({
            "type": "llm-rubric",
            "value": rubric,
        })

    if not assertions:
        log(f"Warning: no assertions generated for case '{case.get('id', '?')}'")
        return None

    entry["assert"] = assertions
    return entry


def generate_cases_yaml(golden_cases: list[dict], target_manifest: dict) -> str:
    comment = f"# Golden cases exported for {target_manifest.get('target_id', '')}\n"
    source_dir = target_manifest.get("canonical_case_directories", {}).get("golden", "cases/golden")
    comment += f"# Source: {source_dir}\n"
    comment += "# Generated by sdlc-evalops export-promptfoo.py - DO NOT EDIT\n\n"

    lines = [comment]

    for case in golden_cases:
        entry = map_case_to_promptfoo(case, target_manifest)
        if entry is None:
            log(f"Skipped case: {case.get('id', case.get('_file', '?'))} (missing valid assertions)")
            continue
        lines.append(yaml.dump([entry], default_flow_style=False, allow_unicode=True, sort_keys=False))

    return "".join(lines)
